# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy via SSH

on:
  push:
    branches: [ "v3.0.0" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: v15
    - name: Install dependencies
      run: npm install
    - name: Build the frontend
      run: API_URL=https://delaymap.robbevanherck.be/trains npm run build
    - name: Copy to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        source: "dist/*"
        target: "${{ secrets.REMOTE_DIR }}"
